# Uncomment the next line to define a global platform for your project
 platform :ios, '11.10'

inhibit_all_warnings!

target 'OneAppiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'MaterialComponents'
  pod 'RippleEffectView'
  pod 'Alamofire-Synchronous', '~> 4.0'
  pod 'Floaty', '~> 3.0.0' # Use version 4.0.0 for Swift 4.0
  pod 'SwiftyJSON', '~> 4.0'
  pod 'QRCodeReader.swift', '~> 8.1.1'
  pod 'QRCode', '~> 2.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FoldingTabBar'
  
  # Pods for OneAppiOS

  target 'OneAppiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneAppiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
